# Generated by Django 2.2.4 on 2019-08-22 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='ststus',
            new_name='status',
        ),
    ]
